- .github/workflows/google.yml
> Workflow gcp

- .github/workflows/google.yml
- maintemplate/server/Makefile
- maintemplate/server/README.md
- Add cluster setup targets to Makefile
- Add ingress controller deployment to github action
- Update README
Fixes issue: #48
> Add GKE setup required steps

- .github/workflows/google.yml
- maintemplate/server/k8s/http-ingress.yaml
> Let's Encrypt

- maintemplate/client/Makefile
- maintemplate/client/i18n/intl.arb
> update makefile i18n

- mod-chat/server/Makefile
- mod-chat/server/README.md
- mod-chat/server/go.mod
- mod-chat/server/go.sum
update mod-chat makefile
issue #49
> update mod-chat makefile

- maintemplate/server/k8s/jetstream-statefulset.yaml
> Add kubernetes manifests for jetstream

- .github/workflows/google.yml
- maintemplate/client/web/index.html
> Disable flutter web cache

- mod-chat/server/grpc-web/pkg/proto/v3.proto
added Readme file and update protofile to v3
> Architecture for mod-chat

- mod-chat/server/grpc-web/pkg/proto/v3.proto
> update proto file

- mod-chat/client/lib/grpc_web_example/api/chat_service.dart
- mod-write/client/lib/view/src/form.dart
- mod-write/client/lib/view/src/full_page.dart
- mod-write/client/lib/view/src/view.dart
- mod-write/client/lib/view/src/zefyr_image_delegate.dart
- mod-write/client/lib/view/src/zefyr_image_delegate_web.dart
- mod-write/client/pubspec.yaml
https://github.com/getcouragenow/packages/issues/129
> Fixed flutter web dependencies for native

- .github/workflows/build-sign-deploy-desktop copy.yml
- maintemplate/client/Makefile
> added ci asti desktop

- .github/workflows/build-sign-deploy-desktop-electron.yml
- maintemplate/client/.gitignore
- maintemplate/client/Makefile
- maintemplate/client/packer/config/deb.json
- maintemplate/client/packer/go.mod
- maintemplate/client/packer/linux/deb.go
- maintemplate/client/packer/main.go
- maintemplate/client/packer/makefile
update desktop electron ci for linux
> update desktop electron ci for linux

- maintemplate/client/lib/layout_template.dart
- mod-chat-beta/client/.idea/workspace.xml
- mod-chat-beta/client/lib/screens/chat.dart
- mod-chat-beta/client/lib/screens/screenwidget.dart
- mod-chat-beta/client/lib/utils/hive_parse.dart
No idea why the linters didn't catch this...
> Fix LayoutTemplate to work with mod-chat-beta

- .github/workflows/build-sign-deploy-desktop-electron.yml
- maintemplate/client/Makefile
- maintemplate/client/desktop/go.mod
- maintemplate/client/desktop/go.sum
- maintemplate/client/packer/config/win.json
- maintemplate/client/packer/go.mod
- maintemplate/client/packer/go.sum
- maintemplate/client/packer/linux/deb.go
- maintemplate/client/packer/main.go
- maintemplate/client/packer/makefile
- maintemplate/client/packer/utils/utils.go
- maintemplate/client/packer/win/model.go
- maintemplate/client/packer/win/win.go
added windows msi to packer tool
> added windows msi to packer tool

- .github/workflows/build-sign-deploy-desktop-hover.yml
update hover ci for windows, linux and macos, and create releases
issue #313
> PACKAGING: CI update hover ci

- maintemplate/client/lib/generated_plugin_registrant.dart
- maintemplate02/client/lib/mod01/readme.md
- maintemplate02/client/lib/mod02/readme.md
> added readme to maintemplate2 for saad

- .github/workflows/build-sign-deploy-desktop-hover.yml
> test commit

- maintemplate/client/lib/main.dart
- mod-chat/client/lib/grpc_web_example/api/chat_service.dart
I don't think I'm done but the email mentions CI,so I want to see it in action as the local env has some issues.
> Nsepulveda issue 332 a

- maintemplate/client/assets/env.json
- maintemplate/client/lib/modules/settings/view_models/settings_view_model.dart
#360 
Adding Locale support to env.json and settings_view_model.dart
> Issue #360 Adding Locale support to env.json and loader

- .github/workflows/ci.yml
- maintemplate/client/assets/env-template.json
- maintemplate/client/assets/env.json
FOR: #364 
This should complete the locales work relating to #360 
I tested the sed locally and it seemed to work, but, I'm wary about the CI process and how it may be different.
> Issue #364 - Including locales in CI

- maintemplate/client/assets/env-template.json
> #364 Removed bad bracket

- maintemplate/client/lib/app_module.dart
> #374 Moving MainAppModule implementation to named params

- maintemplate/client/lib/app_module.dart
- maintemplate/client/lib/core/routing/router.dart
- mod-main/client/lib/core/routes/paths.dart
- mod-main/client/lib/modules/main_module.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_dashboard_view.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_dashboard_view_desktop.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_dashboard_view_mobile.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_manager_view.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_manager_view_desktop.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_manager_view_mobile.dart
- mod-main/client/lib/modules/org_manager/orgs/widgets/data_pane/data_pane.dart
- mod-main/client/pubspec.yaml
All issues explained here : https://github.com/getcouragenow/packages/pull/371#issuecomment-613568808 are fixed.
- In desktop view .i.e Big screens, data table shows 10 rows max, and provides next and back buttons to paginate
- In mobile view, as u scroll down rows gets loaded. There is no option of next and back pagination in mobile view
- Pagination is working fine now, test please
> Fixes for #294

- mod-main/client/lib/core/shared_repositories/base_repository.dart
- mod-main/client/lib/core/shared_repositories/mocks/mock_org_repository.dart
- mod-main/client/lib/core/shared_repositories/org_repository.dart
- mod-main/client/lib/modules/main_module.dart
- mod-main/client/lib/modules/orgs/data/org_model.dart
- mod-main/client/lib/modules/orgs/service/orgs_service.dart
- mod-main/client/lib/modules/orgs/view_model/org_view_model.dart
- mod-main/client/lib/modules/orgs/views/org_detail_view.dart
- mod-main/client/lib/modules/orgs/views/org_view.dart
- mod-main/client/lib/modules/userinfo/view_model/userinfo_view_model.dart
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
For issue #373 
Orgs are now using repo pattern, UserNeeds is the next tone to work on.
Now that everything has been established, the actual conversion to repository methods will be easier.
Then from there we need to render different "question types" differently.
> Issue #373 - Phase 1 Orgs with repo pattern

- mod-main/client/lib/core/shared_repositories/mocks/mock_org_repository.dart
> #373 Fixed small bug from duplicates ids in mock data

- .github/workflows/build-sign-deploy-desktop-hover.yml
- mod-main/server/.gitignore
- mod-main/server/cmd/client.go
- mod-main/server/cmd/server.go
- mod-main/server/go.sum
- mod-main/server/pkg/service/svc.go
- mod-main/server/pkg/store/minio/minio.go
- fix bugs in mod-main #398 
- fix tag refs/heads/master #389
> PACKAGES: main-mod and desktop CI

- mod-main/server/cmd/client.go
> PACKAGES: mod-main try to fix ci

- mod-main/client/lib/modules/main_module.dart
- mod-main/client/lib/modules/org_manager/orgs/view_model/orgs_detail_page_view_model.dart
- mod-main/client/lib/modules/org_manager/orgs/views/org_detail_page.dart
- mod-main/client/lib/modules/org_manager/orgs/views/org_master_page.dart
- mod-main/client/lib/modules/org_manager/orgs/views/orgs_manager_master_view.dart
> Master detail id fix

- mod-main/client/Makefile
- mod-main/client/lib/api/service.pb.dart
- mod-main/client/lib/api/service.pbenum.dart
- mod-main/client/lib/api/service.pbgrpc.dart
- mod-main/client/lib/api/service.pbjson.dart
- mod-main/server/Makefile
- mod-main/server/pkg/api/service.pb.go
both client and server can be run locally without ANY of the other mods or main template now.
> mod-main make fixes

- maintemplate/client/lib/generated_plugin_registrant.dart
- maintemplate/client/lib/nav_rail.dart
- mod-main/client/lib/core/package/detail_page_wrapper.dart
- mod-main/client/lib/modules/org_manager/orgs/views/org_detail_page.dart
Fixes for https://github.com/getcouragenow/packages/issues/386
> Data pane hidding action buttons fixed

- mod-main/client/lib/core/shared_services/dynamic_widget_service.dart
- mod-main/client/lib/modules/user_needs/view_model/userneed_view_model.dart
- mod-main/client/lib/modules/user_needs/views/user_need_view.dart
#373 
Adding textbox to dynamic fields. This is the final commit of this issue, I've made other issues to break out the work and make it more organized.
> #373 Adding Dynamic Text box

- mod-main/client/lib/core/shared_services/dynamic_widget_service.dart
- mod-main/client/lib/modules/support_roles/view_model/supportRole_view_model.dart
- mod-main/client/lib/modules/support_roles/views/support_role_view.dart
> #411 Adding DynamicSlider to the dynamic widgets

- mod-main/client/Makefile
- mod-main/client/i18n/intl_messages.arb
- mod-main/client/i18n/lang_en.arb
- mod-main/client/i18n/lang_en.json
- mod-main/client/i18n/lang_es.arb
- mod-main/client/i18n/lang_es.json
- mod-main/client/i18n/lang_fr.arb
- mod-main/client/i18n/lang_fr.json
- mod-main/client/i18n/lang_ur.arb
- mod-main/client/i18n/lang_ur.json
- mod-main/client/lib/core/i18n/mod_main_localization.dart
- mod-main/client/lib/core/i18n/translations.dart
- mod-main/client/lib/modules/orgs/views/org_detail_view.dart
- mod-main/client/lib/modules/orgs/views/org_view.dart
- mod-main/client/lib/modules/support_roles/views/support_role_view.dart
- mod-main/client/lib/modules/user_needs/view_model/userneed_view_model.dart
- mod-main/client/lib/modules/user_needs/views/user_need_view.dart
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
> Issue #434 ModMain i18n

- maintemplate/client/lib/main.dart
- mod-account/client/Makefile
- mod-account/client/example/lib/main.dart
- mod-account/client/i18n/intl_messages.arb
- mod-account/client/i18n/lang_en.arb
- mod-account/client/i18n/lang_en.json
- mod-account/client/i18n/lang_es.arb
- mod-account/client/i18n/lang_es.json
- mod-account/client/i18n/lang_fr.arb
- mod-account/client/i18n/lang_fr.json
- mod-account/client/i18n/lang_ur.arb
- mod-account/client/i18n/lang_ur.json
- mod-account/client/lib/core/core.dart
- mod-account/client/lib/core/i18n/mod_account_localization.dart
- mod-account/client/lib/core/i18n/translations.dart
- mod-account/client/lib/modules/signup/views/signup_view.dart
- mod-account/client/pubspec.yaml
#440
ModAccount i18n implementation
> Issue #440 ModAccount i18n implementation

- mod-account/client/lib/core/i18n/mod_account_localization.dart
- mod-chat/client/lib/core/i18n/mod_chat_localization.dart
- mod-main/client/lib/core/i18n/mod_main_localization.dart
> #449 Adjusting localization json path

- .github/workflows/ci.yml
> #460 adding languages to CI

- maintemplate/server/Makefile
- maintemplate/server/README.md
- maintemplate/server/scripts/local-dev-setup.sh
```make install-prequisites``` for short
> added scripts to install prequisites for macs and linux #456

- maintemplate/server/ENV
- maintemplate/server/Makefile
- maintemplate/server/README.md
- maintemplate/server/deployments/helm/templates/flutter-deployment.yaml
- maintemplate/server/deployments/helm/values.yaml
- maintemplate/server/go.mod
- maintemplate/server/local-ssl/scripts/gen-certs.sh
- maintemplate/server/scripts/insecure-registries.sh
- maintemplate/server/scripts/local-dev-setup.sh
- maintemplate/server/scripts/source-env.sh
> Fixes minikube problem when running on both linux and macos host.

- .github/workflows/beta.yml
- .github/workflows/ci.yml
- .github/workflows/dev.yml
- maintemplate/server/deployments/minio/ingress.yaml
Fixes issue no #468 
Sed didn't actually replace any value in the CI / beta workflow, it is now fixed.
> fixes CI and Beta builds

- .github/workflows/ci.yml
> revert back to sed from perl in ci

- .github/workflows/ci.yml
> fixes yaml lint error

- maintemplate/client/lib/modules/settings/view_models/settings_view_model.dart
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
- mod-timespace/client/example/lib/main.dart
- mod-timespace/client/lib/mod_timespace.dart
- mod-timespace/client/lib/src/views/search_location_widget.dart
- mod-timespace/client/pubspec.yaml
will be visible in /userinfo (mod-main)
Widget works with autocompletion on location text and shows the result on a map. Works on WEB and Native
live data is not working! Only mock data - since the free openstreet view endpoint shut down during development.
> #470 SearchLocationWidget added to mod-timespace

- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
- mod-timespace/client/lib/src/views/search_location_widget.dart
> #470 added debug flag for SearchLocationWidget

- mod-main/client/lib/core/shared_services/dynamic_widget_service.dart
> #492 dropdown spacing fix

- mod-main/client/lib/modules/support_roles/views/support_role_view.dart
- mod-timespace/client/lib/src/views/search_location_widget.dart
> #494 mod-main searchlocation /userinfo keyboard opened on zoom fix

- mod-main/client/i18n/intl_messages.arb
- mod-main/client/i18n/lang_en.arb
- mod-main/client/i18n/lang_en.json
- mod-main/client/lib/core/i18n/translations.dart
- mod-main/client/lib/modules/orgs/views/org_detail_view.dart
- mod-main/client/lib/modules/orgs/views/org_view.dart
- mod-main/client/lib/modules/user_needs/views/user_need_view.dart
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
- sys-core/client/lib/src/widgets/gc_master_detail.dart
> #506 appbar title adjustments, #473 master detail width fix

- mod-main/client/i18n/intl_messages.arb
- mod-main/client/i18n/lang_de.json
- mod-main/client/i18n/lang_en.json
- mod-main/client/i18n/lang_es.json
- mod-main/client/i18n/lang_fr.json
- mod-main/client/i18n/lang_it.json
- mod-main/client/i18n/lang_ur.json
- mod-main/client/lib/modules/userinfo/view_model/userinfo_view_model.dart
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
As per #508 and Telegram discussion :)
> Added "About You" to intl and brought back userinfo questions (#508)

- mod-main/client/i18n/intl_messages.arb
- mod-main/client/i18n/lang_de.arb
- mod-main/client/i18n/lang_de.json
- mod-main/client/i18n/lang_en.arb
- mod-main/client/i18n/lang_en.json
- mod-main/client/i18n/lang_es.arb
- mod-main/client/i18n/lang_es.json
- mod-main/client/i18n/lang_fr.arb
- mod-main/client/i18n/lang_fr.json
- mod-main/client/i18n/lang_it.arb
- mod-main/client/i18n/lang_it.json
- mod-main/client/i18n/lang_ur.arb
- mod-main/client/i18n/lang_ur.json
- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
> Complete mod-main userInfo intl; as per #511

- mod-main/client/lib/modules/userinfo/views/userinfo_view.dart
Bugifx for PR #523 ; Issue #511
> Bugfix for userInfo translation (#511)

- maintemplate/client/lib/layout_template.dart
- maintemplate/client/lib/nav_rail.dart
> #517 rail overflow for certain languages

- maintemplate/client/lib/layout_template.dart
- maintemplate/client/lib/nav_rail.dart
- mod-write/client/lib/home_screen.dart
- mod-write/client/lib/view/list_document.dart
- mod-write/client/lib/view/list_document_old_hack.dart
- mod-write/client/lib/view/src/full_page.dart
- mod-write/client/lib/writer_module.dart
- mod-write/client/pubspec.yaml
- sys-core/client/lib/src/device_utils.dart
> #517 nav rail width flexible, smaller master view breakpoint 

- mod-write/client/lib/core/routes/paths.dart
> #517 broken build fix

- mod-main/client/lib/modules/org_manager/orgs/views/org_master_detail_view.dart
- mod-write/client/lib/view/list_document.dart
- sys-core/client/lib/src/widgets/gc_master_detail.dart
> #517 master detail more abstracted with flexible master width

- sys-core/client/lib/src/widgets/gc_master_detail.dart
MasterView was slightly cut off on some devices (specially with a nodge). Now it's fixed. 
#517
> #517 fixed master view cut off on some devices

- mod-main/client/example/pubspec.yaml
- mod-main/client/lib/modules/org_manager/orgs/views/org_master_detail_view.dart
- mod-main/client/lib/modules/orgs/views/org_view.dart
- mod-main/client/lib/modules/support_roles/views/support_role_view.dart
> #559 small master/detail layout fixes

- mod-kanban/client/example/lib/main.dart
- mod-kanban/client/i18n/intl_messages.arb
- mod-kanban/client/i18n/lang_de.arb
- mod-kanban/client/i18n/lang_de.json
- mod-kanban/client/i18n/lang_en.arb
- mod-kanban/client/i18n/lang_en.json
- mod-kanban/client/i18n/lang_es.arb
- mod-kanban/client/i18n/lang_es.json
- mod-kanban/client/i18n/lang_fr.arb
- mod-kanban/client/i18n/lang_fr.json
- mod-kanban/client/i18n/lang_it.arb
- mod-kanban/client/i18n/lang_it.json
- mod-kanban/client/i18n/lang_ur.arb
- mod-kanban/client/i18n/lang_ur.json
- mod-kanban/client/lib/core/i18n/translations.dart
- mod-kanban/client/lib/view/home_screen.dart
- mod-kanban/client/pubspec.yaml
> Use the Reorderablelistview from the flutter sdk itself. So we can scroll vertically and drag and drop items (with a long press).
Started to just use the old behaviour but with longpress. I noticed that the ordering was very buggy so switchted to flutter out-of-the-box Reorderablelistview and it works good!
> Add item button (currently there is no way to add an item)
Added.
> Fix the theming for dark mode (some texts are colored white on white background)
Fixed for light & darkmode. The top-level theming is used (see Screenshots).
Additional:
Localised all used Strings.
> #512 mod-kanban fixing

- boilerplate/flu.mk
- maintemplate/client/pubspec.yaml
- mod-account/client/example/pubspec.yaml
- mod-account/client/pubspec.yaml
- mod-chat/Makefile
- mod-chat/client/example/go/.gitignore
- mod-chat/client/example/lib/main.dart
- mod-chat/client/example/pubspec.yaml
- mod-chat/client/lib/mod_chat.dart
- mod-chat/client/pubspec.yaml
- mod-chat/server/Makefile
- mod-chat/server/go.mod
- mod-chat/server/go.sum
- mod-geo/client/pubspec.yaml
- mod-ion/client/example/pubspec.yaml
- mod-ion/client/pubspec.yaml
- mod-kanban/client/example/pubspec.yaml
- mod-kanban/client/pubspec.yaml
- mod-main/client/example/pubspec.yaml
- mod-main/client/pubspec.yaml
- mod-write/client/example/pubspec.yaml
- mod-write/client/pubspec.yaml
- server-infa/README.md
- server-infa/k3d/README.md
- server-infa/k3d/makefile
> Flutter Mod upgrade, but still broken.

- maintemplate/makefile
just a little make file voodu
lang trans works too for everything
> maintemplate works

- sys-core/server/go.mod
- sys-core/server/pkg/db/db.go
- sys-core/server/pkg/db/init.go
- sys-core/server/test/db_test.go
- sys-core/server/test/encrypt_test.go
- Move the encrypt key to the .yml file later.
> Enable encryption for badger db.
